Name:               alertmanager-stable-kube-prometheus-sta-alertmanager
Namespace:          default
CreationTimestamp:  Sun, 16 Feb 2025 22:07:29 +0530
Selector:           alertmanager=stable-kube-prometheus-sta-alertmanager,app.kubernetes.io/instance=stable-kube-prometheus-sta-alertmanager,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=alertmanager
Labels:             app=kube-prometheus-stack-alertmanager
                    app.kubernetes.io/instance=stable
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/part-of=kube-prometheus-stack
                    app.kubernetes.io/version=69.3.1
                    chart=kube-prometheus-stack-69.3.1
                    heritage=Helm
                    managed-by=prometheus-operator
                    release=stable
Annotations:        meta.helm.sh/release-name: stable
                    meta.helm.sh/release-namespace: default
                    prometheus-operator-input-hash: 6763692469760526627
Replicas:           1 desired | 1 total
Update Strategy:    RollingUpdate
Pods Status:        1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           alertmanager=stable-kube-prometheus-sta-alertmanager
                    app.kubernetes.io/instance=stable-kube-prometheus-sta-alertmanager
                    app.kubernetes.io/managed-by=prometheus-operator
                    app.kubernetes.io/name=alertmanager
                    app.kubernetes.io/version=0.28.0
  Annotations:      kubectl.kubernetes.io/default-container: alertmanager
  Service Account:  stable-kube-prometheus-sta-alertmanager
  Init Containers:
   init-config-reloader:
    Image:      quay.io/prometheus-operator/prometheus-config-reloader:v0.80.0
    Port:       8081/TCP
    Host Port:  0/TCP
    Command:
      /bin/prometheus-config-reloader
    Args:
      --watch-interval=0
      --listen-address=:8081
      --config-file=/etc/alertmanager/config/alertmanager.yaml.gz
      --config-envsubst-file=/etc/alertmanager/config_out/alertmanager.env.yaml
      --watched-dir=/etc/alertmanager/config
    Environment:
      POD_NAME:   (v1:metadata.name)
      SHARD:     -1
    Mounts:
      /etc/alertmanager/config from config-volume (ro)
      /etc/alertmanager/config_out from config-out (rw)
      /etc/alertmanager/web_config/web-config.yaml from web-config (ro,path="web-config.yaml")
  Containers:
   alertmanager:
    Image:       quay.io/prometheus/alertmanager:v0.28.0
    Ports:       9093/TCP, 9094/TCP, 9094/UDP
    Host Ports:  0/TCP, 0/TCP, 0/UDP
    Args:
      --config.file=/etc/alertmanager/config_out/alertmanager.env.yaml
      --storage.path=/alertmanager
      --data.retention=120h
      --cluster.listen-address=
      --web.listen-address=:9093
      --web.external-url=http://stable-kube-prometheus-sta-alertmanager.default:9093
      --web.route-prefix=/
      --cluster.label=default/stable-kube-prometheus-sta-alertmanager
      --cluster.peer=alertmanager-stable-kube-prometheus-sta-alertmanager-0.alertmanager-operated:9094
      --cluster.reconnect-timeout=5m
      --web.config.file=/etc/alertmanager/web_config/web-config.yaml
    Requests:
      memory:   200Mi
    Liveness:   http-get http://:http-web/-/healthy delay=0s timeout=3s period=10s #success=1 #failure=10
    Readiness:  http-get http://:http-web/-/ready delay=3s timeout=3s period=5s #success=1 #failure=10
    Environment:
      POD_IP:   (v1:status.podIP)
    Mounts:
      /alertmanager from alertmanager-stable-kube-prometheus-sta-alertmanager-db (rw)
      /etc/alertmanager/certs from tls-assets (ro)
      /etc/alertmanager/config from config-volume (rw)
      /etc/alertmanager/config_out from config-out (ro)
      /etc/alertmanager/web_config/web-config.yaml from web-config (ro,path="web-config.yaml")
   config-reloader:
    Image:      quay.io/prometheus-operator/prometheus-config-reloader:v0.80.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Command:
      /bin/prometheus-config-reloader
    Args:
      --listen-address=:8080
      --web-config-file=/etc/alertmanager/web_config/web-config.yaml
      --reload-url=http://127.0.0.1:9093/-/reload
      --config-file=/etc/alertmanager/config/alertmanager.yaml.gz
      --config-envsubst-file=/etc/alertmanager/config_out/alertmanager.env.yaml
      --watched-dir=/etc/alertmanager/config
    Environment:
      POD_NAME:   (v1:metadata.name)
      SHARD:     -1
    Mounts:
      /etc/alertmanager/config from config-volume (ro)
      /etc/alertmanager/config_out from config-out (rw)
      /etc/alertmanager/web_config/web-config.yaml from web-config (ro,path="web-config.yaml")
  Volumes:
   config-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alertmanager-stable-kube-prometheus-sta-alertmanager-generated
    Optional:    false
   tls-assets:
    Type:                Projected (a volume that contains injected data from multiple sources)
    SecretName:          alertmanager-stable-kube-prometheus-sta-alertmanager-tls-assets-0
    SecretOptionalName:  <nil>
   config-out:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
   web-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alertmanager-stable-kube-prometheus-sta-alertmanager-web-config
    Optional:    false
   alertmanager-stable-kube-prometheus-sta-alertmanager-db:
    Type:          EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:        
    SizeLimit:     <unset>
  Node-Selectors:  <none>
  Tolerations:     <none>
Volume Claims:     <none>
Events:
  Type    Reason            Age   From                    Message
  ----    ------            ----  ----                    -------
  Normal  SuccessfulCreate  59m   statefulset-controller  create Pod alertmanager-stable-kube-prometheus-sta-alertmanager-0 in StatefulSet alertmanager-stable-kube-prometheus-sta-alertmanager successful
